### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by gmodarelli** [moonmaster9000/specdown#2]
Hi Matt

I get a LoadError when I add require "todo" to the specdown/env.rb file.
The file todo.rb is in the folder.

That's the folder's tree

Todo
    specdown
        env.rb
    readme.markdown
    todo.rb

This is the full trace

> /home/giuseppe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require': no such file to load -- todo (LoadError)
> from /home/giuseppe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
> from /home/giuseppe/Documents/LearningProjects/Todo/specdown/env.rb: 1 :in '<top (required)>'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/gems/specdown-0.3.0/lib/specdown/command.rb:16:in 'load'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/gems/specdown-0.3.0/lib/specdown/command.rb:16:in 'block in load_test_environment'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/gems/specdown-0.3.0/lib/specdown/command.rb:15:in 'each'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/gems/specdown-0.3.0/lib/specdown/command.rb:15:in 'load_test_environment'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/gems/specdown-0.3.0/lib/specdown/command.rb: 4 :in 'execute'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/gems/specdown-0.3.0/bin/specdown: 4 :in '<top (required)>'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/bin/specdown:19:in 'load'
> from /home/giuseppe/.rvm/gems/ruby-1.9.2-p290@global/bin/specdown:19:in '<main>'

Thank you ;)

**Comment by moonmaster9000** [comment]
Hi, don't know if you saw my email reply, but anyways, i've also updated the README: https://github.com/moonmaster9000/specdown/commit/245c3413ecde8f8d58516dce9ca79f3d6ae8d791

**Comment by gmodarelli** [comment]
Thank you for this fix ;)
I can't wait to try specdown

Bye!
